# Generated by Django 5.0.4 on 2026-07-01 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadeddocument",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="cases.case",
            ),
        ),
    ]
