# Generated by Django 5.0.4 on 2026-07-01 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("api", "0002_uploadeddocument_case"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadeddocument",
            name="firm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="accounts.firm",
            ),
        ),
    ]
