# Generated by Django 5.0.4 on 2026-07-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_uploadeddocument_firm"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadeddocument",
            name="extracted_entities",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="uploadeddocument",
            name="tags",
            field=models.CharField(
                blank=True, default="", help_text="Comma-separated", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="uploadeddocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("scanned_pdf", "Scanned PDF"),
                    ("docx", "DOCX"),
                    ("txt", "TXT"),
                    ("md", "Markdown"),
                    ("pptx", "PowerPoint"),
                    ("jpg", "JPEG Image"),
                    ("jpeg", "JPEG Image"),
                    ("png", "PNG Image"),
                ],
                max_length=30,
            ),
        ),
    ]
