# Generated by Django 5.0.4 on 2026-07-07 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_firm_is_active"),
        ("api", "0004_uploadeddocument_extracted_entities_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="firm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_messages",
                to="accounts.firm",
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chats",
                to="api.uploadeddocument",
            ),
        ),
    ]
