# Generated by Django 5.0.4 on 2026-07-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_chatmessage_firm_alter_chatmessage_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadeddocument",
            name="drive_file_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="uploadeddocument",
            name="drive_modified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadeddocument",
            name="source",
            field=models.CharField(
                choices=[("upload", "Manual Upload"), ("drive", "Google Drive")],
                default="upload",
                max_length=10,
            ),
        ),
    ]
