# Generated by Django 5.0.4 on 2026-07-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_chatmessage_options_chatsession_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadeddocument",
            name="error_message",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="uploadeddocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="ready",
                max_length=20,
            ),
        ),
    ]
