# Generated by Django 5.0.4 on 2026-07-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_uploadeddocument_error_message_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("flawed_answer", models.TextField()),
                (
                    "lesson",
                    models.TextField(
                        help_text="Short, general instruction derived from the mistake."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
