# Generated by Django 5.0.4 on 2026-07-13 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_agentlesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadeddocument",
            name="previous_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_versions",
                to="api.uploadeddocument",
            ),
        ),
        migrations.AddField(
            model_name="uploadeddocument",
            name="version_number",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
