# Generated by Django 5.0.4 on 2026-07-14 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_uploadeddocument_previous_version_and_more"),
        ("cases", "0003_case_drive_link_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="active_case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cases.case",
            ),
        ),
    ]
