# Generated by Django 5.0.4 on 2026-07-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_chatsession_active_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='edited_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
