# Generated by Django 5.0.4 on 2026-07-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_uploadeddocument_edited_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
