# Generated by Django 5.0.4 on 2026-07-30 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_lawyerprofile_role_firmllmconfig_and_more'),
        ('api', '0015_chatmessage_cached_chatmessage_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='cached',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='region',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='asked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.lawyerprofile'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sources',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='SelfLearnedEntry',
        ),
    ]
