# Generated by Django 5.0.4 on 2026-07-30 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_chatmessage_cached_remove_chatmessage_region_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgentLesson',
        ),
    ]
