# Generated by Django 5.0.4 on 2026-07-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="firm",
            name="size",
            field=models.CharField(
                choices=[
                    ("solo", "Solo (just me)"),
                    ("small", "Small (2-10 lawyers)"),
                    ("mid", "Mid-size (11-50 lawyers)"),
                    ("large", "Large (50+ lawyers)"),
                ],
                default="solo",
                max_length=10,
            ),
        ),
    ]
