# Generated by Django 5.0.4 on 2026-07-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_firm_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="firm",
            name="address",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="firm",
            name="bar_registration_number",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="firm",
            name="official_email_domain",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
