# Generated by Django 5.0.4 on 2026-07-07 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_firm_address_firm_bar_registration_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="firm",
            name="employee_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="firm",
            name="gst_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="firm",
            name="lawyer_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="firm",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="firm_logos/"),
        ),
        migrations.AddField(
            model_name="firm",
            name="office_locations",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="firm",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="firm",
            name="practice_areas",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Comma-separated, e.g. 'Corporate, Civil, Family'",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="firm",
            name="website",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="lawyerprofile",
            name="department",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="firm",
            name="size",
            field=models.CharField(
                choices=[
                    ("solo", "Solo (just me)"),
                    ("small", "Small (2-10 lawyers)"),
                    ("mid", "Medium (11-50 lawyers)"),
                    ("large", "Large (51-200 lawyers)"),
                    ("enterprise", "Enterprise (200+ lawyers)"),
                ],
                default="solo",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("details", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_actions",
                        to="accounts.lawyerprofile",
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="accounts.firm",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
