# Generated by Django 5.0.4 on 2026-07-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_firm_employee_count_firm_gst_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="firm",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Suspended firms cannot log in - enforced in JWTAuth.",
            ),
        ),
    ]
