# Generated by Django 5.0.4 on 2026-07-08 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_firm_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleDriveConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField()),
                ("token_expiry", models.DateTimeField(blank=True, null=True)),
                ("folder_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "folder_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("folder_link", models.URLField(blank=True, default="")),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "connected_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.lawyerprofile",
                    ),
                ),
                (
                    "firm",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drive_connection",
                        to="accounts.firm",
                    ),
                ),
            ],
        ),
    ]
