# Generated by Django 5.0.4 on 2026-07-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_googledriveconnection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googledriveconnection",
            name="access_token",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="googledriveconnection",
            name="refresh_token",
            field=models.TextField(blank=True, default=""),
        ),
    ]
