# Generated by Django 5.0.4 on 2026-07-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_firm_default_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lawyerprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Firm Admin"),
                    ("partner", "Partner"),
                    ("associate", "Associate"),
                    ("paralegal", "Paralegal"),
                    ("public", "Public User"),
                ],
                default="associate",
                max_length=20,
            ),
        ),
    ]
