# Generated by Django 5.0.4 on 2026-07-17 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_firm_default_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lawyerprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Firm Admin"),
                    ("partner", "Partner"),
                    ("associate", "Associate"),
                    ("paralegal", "Paralegal"),
                    ("public", "Public User"),
                ],
                default="associate",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="FirmSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "firm",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="accounts.firm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RolePermissionOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Firm Admin"),
                            ("partner", "Partner"),
                            ("associate", "Associate"),
                            ("paralegal", "Paralegal"),
                            ("public", "Public User"),
                        ],
                        max_length=20,
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("granted", models.BooleanField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_overrides",
                        to="accounts.firm",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.lawyerprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("firm", "role", "action")},
            },
        ),
    ]
