# Generated by Django 5.0.4 on 2026-07-21 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_firm_default_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Firm Admin'), ('partner', 'Partner'), ('associate', 'Associate'), ('paralegal', 'Paralegal'), ('public', 'Public User')], default='associate', max_length=20),
        ),
        migrations.CreateModel(
            name='FirmLLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('groq', 'Groq'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('gemini', 'Google Gemini')], max_length=20)),
                ('api_key', models.TextField()),
                ('model_name', models.CharField(blank=True, default='', help_text='Optional override; empty means the provider/platform default model.', max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.lawyerprofile')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_configs', to='accounts.firm')),
            ],
        ),
        migrations.AddConstraint(
            model_name='firmllmconfig',
            constraint=models.UniqueConstraint(fields=('firm', 'provider'), name='unique_llm_provider_per_firm'),
        ),
    ]
