# Generated by Django 5.0.4 on 2026-07-20 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_lawyerprofile_role_firmsettings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="firm",
            name="ai_provider_mode",
            field=models.CharField(
                choices=[
                    ("platform_managed", "Platform Managed (SaaS)"),
                    ("customer_managed", "Customer Managed (Bring Your Own API Key)"),
                ],
                default="platform_managed",
                help_text="Which API keys pay for this firm's AI requests. platform_managed (default) uses the platform's own keys - customer_managed routes every AI request through the firm's own connected provider credential instead. Never both at once - see rag/llm_client.py.",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AIProviderCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("google_gemini", "Google Gemini"),
                            ("azure_openai", "Azure OpenAI"),
                            ("groq", "Groq"),
                            ("mistral", "Mistral"),
                        ],
                        max_length=20,
                    ),
                ),
                ("encrypted_api_key", models.TextField()),
                ("base_url", models.CharField(blank=True, default="", max_length=500)),
                ("model", models.CharField(blank=True, default="", max_length=200)),
                ("extra_config", models.JSONField(blank=True, default=dict)),
                ("enabled", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("untested", "Untested"),
                            ("connected", "Connected"),
                            ("failed", "Failed"),
                        ],
                        default="untested",
                        max_length=10,
                    ),
                ),
                ("last_tested_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_test_message",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.lawyerprofile",
                    ),
                ),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_provider_credentials",
                        to="accounts.firm",
                    ),
                ),
            ],
            options={
                "unique_together": {("firm", "provider")},
            },
        ),
    ]
