# Generated by Django 5.0.4 on 2026-08-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_lawyerprofile_role_firmllmconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='default_region',
            field=models.CharField(choices=[('india', 'India'), ('usa', 'United States'), ('uk', 'United Kingdom'), ('canada', 'Canada'), ('australia', 'Australia'), ('singapore', 'Singapore'), ('eu', 'European Union'), ('middle_east', 'Middle East')], default='usa', help_text="Jurisdiction used for web search when a question doesn't specify one.", max_length=20),
        ),
    ]
