from typing import Optional

from rag.drafting import generate_draft as _generate_draft_text

from .registry import ToolContext, ToolResult, result_json, tool


@tool(
    name="generate_draft",
    description=(
        "Generate a legal draft document (notice, letter, agreement clause, "
        "etc.) and save it to the firm's Drafts page. Only call this when "
        "the user explicitly asks for a document to be drafted/written/"
        "prepared - never as a side effect of answering an informational "
        "question."
    ),
    parameters={
        "type": "object",
        "properties": {
            "title": {"type": "string"},
            "prompt": {
                "type": "string",
                "description": "Detailed instructions for what the draft should contain.",
            },
            "case_id": {
                "type": "integer",
                "description": "Optional - link the draft to a specific case if one is relevant.",
            },
        },
        "required": ["title", "prompt"],
    },
    permission="generate_draft",
)
def generate_draft(ctx: ToolContext, title: str, prompt: str, case_id: Optional[int] = None) -> ToolResult:
    """Mirrors drafts/api.py's generate_draft_endpoint side effects (real
    Draft row, CaseActivity when case-linked) so agent drafts appear in the
    Drafts page like any other."""
    from cases.models import Case, CaseActivity
    from drafts.models import Draft

    case = None
    if case_id:
        try:
            case = Case.objects.get(id=case_id, firm=ctx.firm)
        except Case.DoesNotExist:
            return ToolResult(content=result_json({"error": "Case not found."}))

    context = case.description if case else ""
    content = _generate_draft_text(prompt=prompt, context=context)

    draft = Draft.objects.create(
        firm=ctx.firm,
        case=case,
        draft_type="draft",
        title=title,
        prompt=prompt,
        content=content,
        created_by=ctx.user,
    )

    if case:
        CaseActivity.objects.create(
            case=case,
            actor=ctx.user,
            activity_type="draft_generated",
            body=f"Draft generated by AI agent: {draft.title}",
        )

    return ToolResult(
        content=result_json({"draft_id": draft.id, "title": draft.title, "content": content}),
        sources=[{"source_type": "draft", "draft_id": draft.id, "draft_title": draft.title}],
    )
