"""
Django settings for legal_ai project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
from dotenv import load_dotenv
import os

load_dotenv()

# Load the local sentence-transformers embedding model from cache without
# contacting the HuggingFace Hub on every startup. Without this, an HF Hub
# outage (reproduced live: HTTP 504s / connection timeouts to huggingface.co)
# makes the model do a slow online HEAD check with 5 retries and backoff on
# EVERY embedding-backed request, so document/agent questions hang for
# minutes even though the model is already downloaded locally. Uses
# setdefault so a fresh machine that still needs to download the model once
# can override it with HF_HUB_OFFLINE=0 in the environment.
os.environ.setdefault("HF_HUB_OFFLINE", "1")
os.environ.setdefault("TRANSFORMERS_OFFLINE", "1")

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Falls back to the original dev-only key so local `runserver` behavior is
# unchanged - any real deployment MUST set DJANGO_SECRET_KEY in its own
# environment (never commit a production key to source).
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-0!od!)wr2pec09t%a)kp4+dc@i@csg*8i3dd0%$we(k-*-o9vx",
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to True to preserve current local dev behavior - any real
# deployment MUST set DJANGO_DEBUG=False in its own environment.
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "remedial-paternal-washcloth.ngrok-free.dev",
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",

    "api",
    "accounts",
    "cases",
    "drafts",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",

]

ROOT_URLCONF = "legal_ai.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "legal_ai.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

VECTOR_DB_DIR = BASE_DIR / "vector_db"
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
CORS_ALLOW_ALL_ORIGINS = True


GROQ_API_KEY = os.getenv("GROQ_API_KEY")
GROQ_MODEL = os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile")

# Symmetric key (Fernet) used to encrypt customer-supplied BYOK AI provider
# API keys at rest - see accounts/encryption.py. Generate one with:
#   python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
AI_CREDENTIAL_ENCRYPTION_KEY = os.getenv("AI_CREDENTIAL_ENCRYPTION_KEY")

EMBEDDING_MODEL = os.getenv(
    "EMBEDDING_MODEL",
    "sentence-transformers/all-MiniLM-L6-v2"
)

RAG_RELEVANCE_DISTANCE_THRESHOLD = float(
    os.getenv("RAG_RELEVANCE_DISTANCE_THRESHOLD", "0.72")
)

# A stricter distance cutoff used ONLY to decide "does the firm actually
# have a genuinely relevant local document for this question?" - the
# question that gates whether the agent offers a web search. The main
# threshold above (0.72) is deliberately loose so the answer pipeline still
# feeds borderline context to the LLM, but it's too loose for the
# grounding/web-consent decision: boilerplate clauses present in almost
# every contract (governing law, jurisdiction, termination) are semantic
# near-misses for any legal-sounding question and score ~0.55-0.70, just
# under 0.72. Measured live, genuinely relevant matches land <=0.45 while
# off-topic boilerplate lands >=0.55, so 0.55 cleanly separates them. When
# the best local match is weaker than this, the agent treats the question
# as "nothing relevant found locally" and offers a web search instead of
# silently answering from the model's own general knowledge.
RAG_STRONG_GROUNDING_DISTANCE_THRESHOLD = float(
    os.getenv("RAG_STRONG_GROUNDING_DISTANCE_THRESHOLD", "0.55")
)

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=8),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
}

# Email (lawyer invite links). Defaults target Brevo's free SMTP relay
# (300 emails/day, no domain verification needed to start) - get SMTP
# credentials from Brevo > Settings > SMTP & API > SMTP, and set
# EMAIL_HOST_USER / EMAIL_HOST_PASSWORD / DEFAULT_FROM_EMAIL in .env.
# DEFAULT_FROM_EMAIL must be a verified sender in Brevo. Falls back to
# printing emails to the console if EMAIL_HOST_USER is not configured, so
# invites still work (link visible in the server log) during local dev.
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend"
    if EMAIL_HOST_USER
    else "django.core.mail.backends.console.EmailBackend",
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp-relay.brevo.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER or "noreply@legalai.local")

FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:3000")

GOOGLE_OAUTH_CLIENT_ID = os.getenv("GOOGLE_OAUTH_CLIENT_ID", "")
GOOGLE_OAUTH_CLIENT_SECRET = os.getenv("GOOGLE_OAUTH_CLIENT_SECRET", "")
GOOGLE_OAUTH_REDIRECT_URI = os.getenv(
    "GOOGLE_OAUTH_REDIRECT_URI",
    "http://127.0.0.1:8000/api/integrations/google-drive/callback/",
)
GOOGLE_DRIVE_SCOPES = ["https://www.googleapis.com/auth/drive.readonly"]