# Generated by Django 5.0.4 on 2026-07-20 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0009_alter_lawyerprofile_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceAIConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider_mode",
                    models.CharField(
                        choices=[
                            ("PLATFORM", "Platform Managed (SaaS)"),
                            ("CUSTOMER", "Customer Managed (BYOK)"),
                        ],
                        default="PLATFORM",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_provider_configuration",
                        to="accounts.firm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkspaceAPIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("gemini", "Google Gemini"),
                            ("groq", "Groq"),
                            ("azure_openai", "Azure OpenAI"),
                            ("mistral", "Mistral"),
                        ],
                        max_length=20,
                    ),
                ),
                ("encrypted_api_key", models.TextField()),
                ("base_url", models.CharField(blank=True, default="", max_length=500)),
                ("model", models.CharField(blank=True, default="", max_length=200)),
                ("extra_config", models.JSONField(blank=True, default=dict)),
                ("enabled", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("untested", "Untested"),
                            ("connected", "Connected"),
                            ("failed", "Failed"),
                        ],
                        default="untested",
                        max_length=10,
                    ),
                ),
                ("last_tested_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_test_message",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.lawyerprofile",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_provider_api_keys",
                        to="accounts.firm",
                    ),
                ),
            ],
            options={
                "unique_together": {("workspace", "provider")},
            },
        ),
    ]
