# Generated by Django 5.0.4 on 2026-07-30 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_alter_lawyerprofile_role_firmllmconfig_and_more'),
        ('api', '0016_remove_chatmessage_cached_remove_chatmessage_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('preference', 'Preference'), ('style', 'Style'), ('correction', 'Correction'), ('feedback', 'Feedback'), ('fact', 'Fact')], max_length=12)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.firm')),
                ('source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='accounts.lawyerprofile')),
            ],
            options={
                'verbose_name_plural': 'memory entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], max_length=4)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.firm')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='api.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.lawyerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserStyleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, default='')),
                ('memory_count_at_refresh', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='style_profile', to='accounts.lawyerprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='messagefeedback',
            constraint=models.UniqueConstraint(fields=('message', 'user'), name='uniq_feedback_per_user'),
        ),
    ]
