# Generated by Django 5.0.4 on 2026-07-30 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_alter_lawyerprofile_role_firmllmconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('jurisdiction', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('required_fields', models.JSONField(blank=True, default=list)),
                ('submission_url', models.URLField(blank=True, default='')),
                ('file', models.FileField(blank=True, null=True, upload_to='forms/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.lawyerprofile')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='accounts.firm')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
