# Generated by Django 5.0.4 on 2026-07-20 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_firm_default_region'),
        ('drafts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('sample_file', models.FileField(blank=True, null=True, upload_to='templates/')),
                ('sample_original_name', models.CharField(blank=True, default='', max_length=255)),
                ('sample_text', models.TextField(blank=True, default='')),
                ('extracted_structure', models.TextField(blank=True, default='')),
                ('tone', models.TextField(blank=True, default='')),
                ('formatting_rules', models.TextField(blank=True, default='')),
                ('placeholders', models.JSONField(blank=True, default=list)),
                ('ai_prompt', models.TextField(blank=True, default='')),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_templates', to='accounts.lawyerprofile')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_templates', to='accounts.firm')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='draft',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='drafts.drafttemplate'),
        ),
    ]
