# Generated by Django 5.0.4 on 2026-07-03 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("comment", "Comment"),
                            ("case_created", "Case Created"),
                            ("status_changed", "Status Changed"),
                            ("reminder_added", "Reminder Added"),
                            ("reminder_completed", "Reminder Completed"),
                            ("document_uploaded", "Document Uploaded"),
                            ("draft_generated", "Draft Generated"),
                            ("lawyers_updated", "Assigned Lawyers Updated"),
                        ],
                        default="comment",
                        max_length=30,
                    ),
                ),
                ("body", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="case_activities",
                        to="accounts.lawyerprofile",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="cases.case",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "case activities",
            },
        ),
    ]
